/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs/route'
import { Route as IndexImport } from './routes/index'
import { Route as DocsUpdatingRouteImport } from './routes/docs/updating/route'
import { Route as DocsThirdPartyIntegrationsRouteImport } from './routes/docs/third-party-integrations/route'
import { Route as DocsQuickStartRouteImport } from './routes/docs/quick-start/route'
import { Route as DocsNixRouteImport } from './routes/docs/nix/route'
import { Route as DocsMigrationGuidesRouteImport } from './routes/docs/migration-guides/route'
import { Route as DocsMetadataProvidersRouteImport } from './routes/docs/metadata-providers/route'
import { Route as DocsLibraryStructureRouteImport } from './routes/docs/library-structure/route'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation/route'
import { Route as DocsEmulatorsConfigRouteImport } from './routes/docs/emulators-config/route'
import { Route as DocsConfigurationRouteImport } from './routes/docs/configuration/route'

// Create/Update Routes

const DocsRouteRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DocsUpdatingRouteRoute = DocsUpdatingRouteImport.update({
  id: '/updating',
  path: '/updating',
  getParentRoute: () => DocsRouteRoute,
} as any)

const DocsThirdPartyIntegrationsRouteRoute =
  DocsThirdPartyIntegrationsRouteImport.update({
    id: '/third-party-integrations',
    path: '/third-party-integrations',
    getParentRoute: () => DocsRouteRoute,
  } as any)

const DocsQuickStartRouteRoute = DocsQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => DocsRouteRoute,
} as any)

const DocsNixRouteRoute = DocsNixRouteImport.update({
  id: '/nix',
  path: '/nix',
  getParentRoute: () => DocsRouteRoute,
} as any)

const DocsMigrationGuidesRouteRoute = DocsMigrationGuidesRouteImport.update({
  id: '/migration-guides',
  path: '/migration-guides',
  getParentRoute: () => DocsRouteRoute,
} as any)

const DocsMetadataProvidersRouteRoute = DocsMetadataProvidersRouteImport.update(
  {
    id: '/metadata-providers',
    path: '/metadata-providers',
    getParentRoute: () => DocsRouteRoute,
  } as any,
)

const DocsLibraryStructureRouteRoute = DocsLibraryStructureRouteImport.update({
  id: '/library-structure',
  path: '/library-structure',
  getParentRoute: () => DocsRouteRoute,
} as any)

const DocsInstallationRouteRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRouteRoute,
} as any)

const DocsEmulatorsConfigRouteRoute = DocsEmulatorsConfigRouteImport.update({
  id: '/emulators-config',
  path: '/emulators-config',
  getParentRoute: () => DocsRouteRoute,
} as any)

const DocsConfigurationRouteRoute = DocsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRoute
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof DocsRouteImport
    }
    '/docs/emulators-config': {
      id: '/docs/emulators-config'
      path: '/emulators-config'
      fullPath: '/docs/emulators-config'
      preLoaderRoute: typeof DocsEmulatorsConfigRouteImport
      parentRoute: typeof DocsRouteImport
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRouteImport
    }
    '/docs/library-structure': {
      id: '/docs/library-structure'
      path: '/library-structure'
      fullPath: '/docs/library-structure'
      preLoaderRoute: typeof DocsLibraryStructureRouteImport
      parentRoute: typeof DocsRouteImport
    }
    '/docs/metadata-providers': {
      id: '/docs/metadata-providers'
      path: '/metadata-providers'
      fullPath: '/docs/metadata-providers'
      preLoaderRoute: typeof DocsMetadataProvidersRouteImport
      parentRoute: typeof DocsRouteImport
    }
    '/docs/migration-guides': {
      id: '/docs/migration-guides'
      path: '/migration-guides'
      fullPath: '/docs/migration-guides'
      preLoaderRoute: typeof DocsMigrationGuidesRouteImport
      parentRoute: typeof DocsRouteImport
    }
    '/docs/nix': {
      id: '/docs/nix'
      path: '/nix'
      fullPath: '/docs/nix'
      preLoaderRoute: typeof DocsNixRouteImport
      parentRoute: typeof DocsRouteImport
    }
    '/docs/quick-start': {
      id: '/docs/quick-start'
      path: '/quick-start'
      fullPath: '/docs/quick-start'
      preLoaderRoute: typeof DocsQuickStartRouteImport
      parentRoute: typeof DocsRouteImport
    }
    '/docs/third-party-integrations': {
      id: '/docs/third-party-integrations'
      path: '/third-party-integrations'
      fullPath: '/docs/third-party-integrations'
      preLoaderRoute: typeof DocsThirdPartyIntegrationsRouteImport
      parentRoute: typeof DocsRouteImport
    }
    '/docs/updating': {
      id: '/docs/updating'
      path: '/updating'
      fullPath: '/docs/updating'
      preLoaderRoute: typeof DocsUpdatingRouteImport
      parentRoute: typeof DocsRouteImport
    }
  }
}

// Create and export the route tree

interface DocsRouteRouteChildren {
  DocsConfigurationRouteRoute: typeof DocsConfigurationRouteRoute
  DocsEmulatorsConfigRouteRoute: typeof DocsEmulatorsConfigRouteRoute
  DocsInstallationRouteRoute: typeof DocsInstallationRouteRoute
  DocsLibraryStructureRouteRoute: typeof DocsLibraryStructureRouteRoute
  DocsMetadataProvidersRouteRoute: typeof DocsMetadataProvidersRouteRoute
  DocsMigrationGuidesRouteRoute: typeof DocsMigrationGuidesRouteRoute
  DocsNixRouteRoute: typeof DocsNixRouteRoute
  DocsQuickStartRouteRoute: typeof DocsQuickStartRouteRoute
  DocsThirdPartyIntegrationsRouteRoute: typeof DocsThirdPartyIntegrationsRouteRoute
  DocsUpdatingRouteRoute: typeof DocsUpdatingRouteRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsConfigurationRouteRoute: DocsConfigurationRouteRoute,
  DocsEmulatorsConfigRouteRoute: DocsEmulatorsConfigRouteRoute,
  DocsInstallationRouteRoute: DocsInstallationRouteRoute,
  DocsLibraryStructureRouteRoute: DocsLibraryStructureRouteRoute,
  DocsMetadataProvidersRouteRoute: DocsMetadataProvidersRouteRoute,
  DocsMigrationGuidesRouteRoute: DocsMigrationGuidesRouteRoute,
  DocsNixRouteRoute: DocsNixRouteRoute,
  DocsQuickStartRouteRoute: DocsQuickStartRouteRoute,
  DocsThirdPartyIntegrationsRouteRoute: DocsThirdPartyIntegrationsRouteRoute,
  DocsUpdatingRouteRoute: DocsUpdatingRouteRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/configuration': typeof DocsConfigurationRouteRoute
  '/docs/emulators-config': typeof DocsEmulatorsConfigRouteRoute
  '/docs/installation': typeof DocsInstallationRouteRoute
  '/docs/library-structure': typeof DocsLibraryStructureRouteRoute
  '/docs/metadata-providers': typeof DocsMetadataProvidersRouteRoute
  '/docs/migration-guides': typeof DocsMigrationGuidesRouteRoute
  '/docs/nix': typeof DocsNixRouteRoute
  '/docs/quick-start': typeof DocsQuickStartRouteRoute
  '/docs/third-party-integrations': typeof DocsThirdPartyIntegrationsRouteRoute
  '/docs/updating': typeof DocsUpdatingRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/configuration': typeof DocsConfigurationRouteRoute
  '/docs/emulators-config': typeof DocsEmulatorsConfigRouteRoute
  '/docs/installation': typeof DocsInstallationRouteRoute
  '/docs/library-structure': typeof DocsLibraryStructureRouteRoute
  '/docs/metadata-providers': typeof DocsMetadataProvidersRouteRoute
  '/docs/migration-guides': typeof DocsMigrationGuidesRouteRoute
  '/docs/nix': typeof DocsNixRouteRoute
  '/docs/quick-start': typeof DocsQuickStartRouteRoute
  '/docs/third-party-integrations': typeof DocsThirdPartyIntegrationsRouteRoute
  '/docs/updating': typeof DocsUpdatingRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/configuration': typeof DocsConfigurationRouteRoute
  '/docs/emulators-config': typeof DocsEmulatorsConfigRouteRoute
  '/docs/installation': typeof DocsInstallationRouteRoute
  '/docs/library-structure': typeof DocsLibraryStructureRouteRoute
  '/docs/metadata-providers': typeof DocsMetadataProvidersRouteRoute
  '/docs/migration-guides': typeof DocsMigrationGuidesRouteRoute
  '/docs/nix': typeof DocsNixRouteRoute
  '/docs/quick-start': typeof DocsQuickStartRouteRoute
  '/docs/third-party-integrations': typeof DocsThirdPartyIntegrationsRouteRoute
  '/docs/updating': typeof DocsUpdatingRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/configuration'
    | '/docs/emulators-config'
    | '/docs/installation'
    | '/docs/library-structure'
    | '/docs/metadata-providers'
    | '/docs/migration-guides'
    | '/docs/nix'
    | '/docs/quick-start'
    | '/docs/third-party-integrations'
    | '/docs/updating'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/configuration'
    | '/docs/emulators-config'
    | '/docs/installation'
    | '/docs/library-structure'
    | '/docs/metadata-providers'
    | '/docs/migration-guides'
    | '/docs/nix'
    | '/docs/quick-start'
    | '/docs/third-party-integrations'
    | '/docs/updating'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/configuration'
    | '/docs/emulators-config'
    | '/docs/installation'
    | '/docs/library-structure'
    | '/docs/metadata-providers'
    | '/docs/migration-guides'
    | '/docs/nix'
    | '/docs/quick-start'
    | '/docs/third-party-integrations'
    | '/docs/updating'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/docs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/docs": {
      "filePath": "docs/route.tsx",
      "children": [
        "/docs/configuration",
        "/docs/emulators-config",
        "/docs/installation",
        "/docs/library-structure",
        "/docs/metadata-providers",
        "/docs/migration-guides",
        "/docs/nix",
        "/docs/quick-start",
        "/docs/third-party-integrations",
        "/docs/updating"
      ]
    },
    "/docs/configuration": {
      "filePath": "docs/configuration/route.tsx",
      "parent": "/docs"
    },
    "/docs/emulators-config": {
      "filePath": "docs/emulators-config/route.tsx",
      "parent": "/docs"
    },
    "/docs/installation": {
      "filePath": "docs/installation/route.tsx",
      "parent": "/docs"
    },
    "/docs/library-structure": {
      "filePath": "docs/library-structure/route.tsx",
      "parent": "/docs"
    },
    "/docs/metadata-providers": {
      "filePath": "docs/metadata-providers/route.tsx",
      "parent": "/docs"
    },
    "/docs/migration-guides": {
      "filePath": "docs/migration-guides/route.tsx",
      "parent": "/docs"
    },
    "/docs/nix": {
      "filePath": "docs/nix/route.tsx",
      "parent": "/docs"
    },
    "/docs/quick-start": {
      "filePath": "docs/quick-start/route.tsx",
      "parent": "/docs"
    },
    "/docs/third-party-integrations": {
      "filePath": "docs/third-party-integrations/route.tsx",
      "parent": "/docs"
    },
    "/docs/updating": {
      "filePath": "docs/updating/route.tsx",
      "parent": "/docs"
    }
  }
}
ROUTE_MANIFEST_END */
