injectWorkspacePackages: true
packages:
  - packages/*
  - packages/client/web
  - packages/codegen
  - plugins/*
onlyBuiltDependencies:
  - "@bufbuild/buf"
  - core-js-pure
  - esbuild
  - grpc-tools
  - protobufjs
