injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
  - build:desktop
packages:
  - packages/*
  - plugins/*
onlyBuiltDependencies:
  - "@bufbuild/buf"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - core-js-pure
  - esbuild
  - grpc-tools
  - nx
  - "@parcel/watcher"
  - protobufjs
