packages:
  - packages/*
  - plugins/*

catalog:
  '@bufbuild/protobuf': 2.4.0
  '@eslint/js': ^10.0.0
  '@monodon/rust': ^2.3.0
  '@nx/eslint': 22.5.1
  '@nx/js': 22.5.1
  '@nx/vite': 22.5.1
  '@nx/vitest': 22.5.1
  '@nx/web': 22.5.1
  '@opentelemetry/api': 1.9.0
  '@opentelemetry/context-zone': 2.0.1
  '@opentelemetry/core': ^2.1.0
  '@opentelemetry/exporter-trace-otlp-http': 0.201.0
  '@opentelemetry/exporter-trace-otlp-proto': 0.201.0
  '@opentelemetry/instrumentation': 0.201.0
  '@opentelemetry/instrumentation-document-load': 0.46.0
  '@opentelemetry/instrumentation-fetch': 0.201.0
  '@opentelemetry/resources': 2.0.1
  '@opentelemetry/sdk-trace-web': 2.0.1
  '@opentelemetry/semantic-conventions': 1.33.0
  '@semantic-release/changelog': ^6.0.3
  '@semantic-release/exec': ^7.1.0
  '@semantic-release/git': ^10.0.1
  '@swc-node/register': 1.11.1
  '@swc/core': 1.15.8
  '@swc/helpers': 0.5.18
  '@tanstack/eslint-plugin-query': ^5.91.4
  '@tanstack/react-virtual': ^3.13.12
  '@tauri-apps/api': 2.8.0
  '@tauri-apps/cli': ^2.8.4
  '@tauri-apps/plugin-dialog': 2.4.0
  '@tauri-apps/plugin-fs': 2.4.2
  '@tauri-apps/plugin-opener': 2.5.0
  '@tauri-apps/plugin-process': 2.3.0
  '@tauri-apps/plugin-shell': 2.3.1
  '@tauri-apps/plugin-updater': 2.9.0
  '@tauri-apps/plugin-upload': 2.3.1
  '@tauri-apps/plugin-window-state': 2.4.0
  '@types/node': ^25.0.0
  '@types/react': ^18
  '@types/react-dom': ^18
  '@types/react-syntax-highlighter': ^15.5.13
  '@uptrace/web': ^1.23.0
  '@vitest/ui': 4.0.9
  bright: ^1.0.0
  conventional-changelog-conventionalcommits: ^9.1.0
  dotenv: ^16.5.0
  eslint: ^9.0.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.5.0
  fs-extra: ^11.3.3
  glob: ^11.1.0
  globals: ^17.3.0
  handlebars: ^4.7.8
  jiti: 2.5.1
  jsdom: ~22.1.0
  markdownlint-cli2: ^0.18.1
  nx: 22.5.1
  nx-mcp: 0.16.0
  prettier: 3.5.3
  react: ^18
  react-dom: ^18
  react-markdown: ^9.0.1
  react-syntax-highlighter: ^15.6.3
  recharts: 2.15.4
  rehype-autolink-headings: ^7.1.0
  rehype-github-alerts: ^4.2.0
  rehype-slug: ^6.0.0
  remark-gfm: ^4.0.1
  remark-toc: ^9.0.0
  semantic-release: ^25.0.2
  tauri-plugin-system-info-api: 2.0.10
  tslib: 2.8.1
  typescript: 5.9.2
  typescript-eslint: ^8.56.0
  vite: ^7.0.0
  vite-plugin-dts: ~4.5.0
  vitest: ^3.0.0
  zustand: ^4.5.5

catalogMode: strict

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - grpc-tools
  - nx
  - '@parcel/watcher'
  - protobufjs

overrides:
  glob: ^11.1.0
  tauri-plugin-system-info-api>valibot: 1.2.0
  vite: 7.3.1
