[workspace]
git_release_enable = false
git_tag_enable = false
release_always = false
semver_check = false
publish_no_verify = true
changelog_update = false
changelog_path = "./CHANGELOG.md"
pr_name = "Release: v{{ version }}"
pr_branch_prefix = 'release/'
pr_labels = ["release"]

[[package]]
name = "retrom-service"
changelog_update = true
changelog_include = [
  'retrom-client',
  'retrom-client-web',
  'retrom-plugin-installer',
  'retrom-plugin-launcher',
  'retrom-plugin-config',
  'retrom-plugin-service-client',
  'retrom-plugin-standalone',
  'retrom-plugin-steam',
]
git_release_enable = true
git_tag_enable = true
git_release_name = "v{{ version }}"
git_tag_name = "v{{ version }}"

[changelog]
commit_parsers = [
  { message = "^feat.*:", group = "Newly Added" },
  { message = "^fix.*:", group = "Bug Fixes" },
]
body = """
## [{{ version | trim_start_matches(pat="v") }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
{%- if commit.scope -%}
- *({{commit.scope}})* {{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
{% else -%}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}
{% endif -%}
{% if commit.body %}
{{ commit.body | indent(first=true) }}\n\n
{% endif %}
{% endfor %}
{% endfor -%}
"""
