import type { Metadata } from "next";
import {
  GameServiceDefinition,
  PlatformServiceDefinition,
} from "@/generated/retrom";
import { Client, createChannel, createClient } from "nice-grpc";
import { Inter } from "next/font/google";
import "./globals.scss";
import { cn } from "@/lib/utils";
import { SideBar } from "./side-bar";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import { Toaster } from "@/components/ui/toaster";
import { Menubar } from "@/components/menubar";
import { ScrollArea } from "@/components/ui/scroll-area";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { games, metadata } = await getGamesWithMetadata();
  const { platforms } = await getPlatforms();

  return (
    <html lang="en">
      <body
        className={cn("bg-background font-sans antialiased", inter.variable)}
      >
        <div className="h-screen max-h-screen relative flex flex-col">
          <Menubar />
          <ResizablePanelGroup direction="horizontal" className="h-full">
            <ResizablePanel defaultSize={25} maxSize={40} className="bg-muted">
              <SideBar
                platforms={platforms}
                games={games}
                metadata={metadata}
              />
            </ResizablePanel>

            <ResizableHandle />

            <ResizablePanel defaultSize={75}>
              <ScrollArea className="h-full max-h-full">
                <main className="pb-16">{children}</main>
              </ScrollArea>
            </ResizablePanel>
          </ResizablePanelGroup>
        </div>
        <Toaster />
      </body>
    </html>
  );
}

async function getGamesWithMetadata() {
  const channel = createChannel("http://localhost:5001");
  const client: Client<GameServiceDefinition> = createClient(
    GameServiceDefinition,
    channel,
  );

  try {
    const getGamesResponse = await client.getGames({
      withMetadata: true,
    });

    channel.close();

    const games = getGamesResponse.games;
    const metadata = getGamesResponse.metadata;

    return { games, metadata, error: null };
  } catch (error) {
    console.error(error);
    return { games: [], metadata: [], error };
  }
}

async function getPlatforms() {
  const channel = createChannel("http://localhost:5001");
  const client: Client<PlatformServiceDefinition> = createClient(
    PlatformServiceDefinition,
    channel,
  );

  try {
    const getPlatformsResponse = await client.getPlatforms({});

    channel.close();

    const platforms = getPlatformsResponse.platforms;

    return { platforms, error: null };
  } catch (error) {
    console.error(error);
    return { platforms: [], error };
  }
}
