services:
  retrom-db:
    image: postgres
    container_name: retrom-db
    hostname: retrom-db
    env_file: ./.env
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      TZ: "America/Los_Angeles"
      PGTZ: "America/Los_Angeles"
      POSTGRES_PASSWORD: ${DB_PASS:-password}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-retrom-dev}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  retrom:
    build:
      context: ../
      dockerfile: docker/service.Dockerfile
    container_name: retrom
    hostname: retrom
    env_file: ./.env
    ports:
      - 5111:5101
      - 3010:3000
    volumes:
      - ${CONTENT_DIR1:-./mock_content/}/:/lib1
      - ${CONTENT_DIR2:-./mock_content_single}:/lib2
      - ${CONFIG_DIR:-./config_dev/}:/config
    depends_on:
      - retrom-db
