[package]
name = "retrom-grpc-service"
resolver = "2"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
description = "The Retrom video game library gRPC service handlers"

[dependencies]
diesel = { workspace = true }
diesel-async = { workspace = true }
retrom-codegen = { workspace = true }
retrom-db = { workspace = true }
retrom-service-common = { workspace = true }
walkdir = { workspace = true }
tonic = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
http = { workspace = true }
tower-http = { workspace = true }
deadpool = { workspace = true }
tonic-reflection = { workspace = true }
tonic-web = { workspace = true }
sanitize-filename = { workspace = true }
bigdecimal = { workspace = true }
regex = { workspace = true }
tempfile = { workspace = true }
chrono = { workspace = true }
