on:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        default: true
    secrets:
      RW_DEPLOY_KEY:
        required: true
      RELEASE_GH_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Enable dry run mode
        default: true

name: Create Release

env:
  DRY_RUN: ${{ inputs.dry-run && 'true' || 'false' }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  nix-template-values:
    name: Get Nix Template Values
    runs-on: ubuntu-latest
    outputs:
      pnpm_deps_hash: ${{ steps.pnpm-store.outputs.pnpm_deps_hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install nix
        uses: DeterminateSystems/determinate-nix-action@v3.16.3

      - name: get pnpm store hash for nix pkg
        id: pnpm-store
        run: |
          nix flake update

          # Both packages use the same pnpm store, so a single hash is sufficient
          # and the service will presumably build faster.
          current_hash="$(nix eval --raw .#retrom-service.pnpmDeps.outputHash)"
          log="$(nix build --rebuild --no-link .#retrom-service 2>&1 || true)"
          new_hash="$(echo "$log" | awk '/got/{print $2}')"

          echo "Log output: $log"
          echo "Current hash: $current_hash"
          echo "New hash: $new_hash"

          if [ ! "$new_hash" = "" ]; then
            echo "pnpm_deps_hash=$new_hash" >> "$GITHUB_OUTPUT"
          else
            echo "pnpm_deps_hash=$current_hash" >> "$GITHUB_OUTPUT"
          fi

  release:
    name: Release
    needs: nix-template-values
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.RW_DEPLOY_KEY }}
          persist-credentials: true

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: check NX cloud access
        id: nx-check
        continue-on-error: true
        run: pnpm nx noop

      - name: disable NX cloud
        if: steps.nx-check.outcome != 'success'
        shell: bash
        run: echo "NX_NO_CLOUD=true" >> "$GITHUB_ENV"

      - name: Build release-related packages
        run: pnpm nx run-many -t build -p retrom-flatpak-release retrom-nix-release

      - name: install Rust stable
        id: rust
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: install cargo-workspaces
        run: cargo install cargo-workspaces@0.3.2

      - name: Create Release
        env:
          PNPM_DEPS_HASH: ${{ needs.nix-template-values.outputs.pnpm_deps_hash }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
        run: |
          pnpm exec semantic-release --ci=true --dry-run="$DRY_RUN"
