on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

name: Populate Release

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

env:
  GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}

jobs:
  get-release-info:
    name: Get Release Info
    outputs:
      release_id: ${{ steps.get_release_id.outputs.release_id }}
      release_body: ${{ steps.get_release_body.outputs.release_body }}
    runs-on: ubuntu-24.04
    steps:
      - name: Get Release ID
        id: get_release_id
        shell: bash
        run: |
          RELEASE_ID="$(gh api repos/jmberesford/retrom/releases --jq '.[] | select(.tag_name == "${{ github.ref_name }}").id')"
          echo "release_id=$RELEASE_ID" >> "$GITHUB_OUTPUT"

      - name: Get Release Body
        id: get_release_body
        shell: bash
        run: |
          RELEASE_BODY="$(gh api repos/jmberesford/retrom/releases --jq '.[] | select(.tag_name == "${{ github.ref_name }}").body')"
          {
            echo 'release_body<<EOF'
            echo "$RELEASE_BODY"
            echo EOF
          } >> "$GITHUB_OUTPUT"

  publish-clients:
    name: Publish Clients
    concurrency:
      group: "publish-clients-${{ github.ref_name }}"
      cancel-in-progress: false
    needs:
      - get-release-info
    uses: ./.github/workflows/publish-clients.yml
    secrets: inherit
    with:
      tag_name: ${{ github.ref_name }}
      release_id: ${{ fromJson(needs.get-release-info.outputs.release_id) }}
      release_body: ${{ needs.get-release-info.outputs.release_body }}

  publish-server-images:
    name: Publish Server Images
    concurrency:
      group: "publish-server-images-${{ github.ref_name }}"
      cancel-in-progress: false
    uses: ./.github/workflows/publish-images.yml
    with:
      tag: ${{ github.ref_name }}
      latest: ${{ !contains(github.ref_name, '-') }}
    secrets: inherit

  cache-nix-packages:
    name: Cache Nix Packages (Cachix)
    concurrency:
      group: "cache-nix-packages-${{ github.ref_name }}"
      cancel-in-progress: false
    uses: ./.github/workflows/build-flake.yml
    secrets: inherit
